#!/bin/bash

initMPS() {
    if [ -f bin/depot_tools/gclient ]
    then
	cd bin
	export PATH=$PATH:`pwd`/depot_tools
	cd depot_tools
	svn up
	cd ../..
    else
	mkdir bin
	cd bin
	svn co http://src.chromium.org/svn/trunk/tools/depot_tools
	export PATH=$PATH:`pwd`/depot_tools
	cd ..
    fi

    if [ -f modpagespeed/src/Makefile ]
    then
	cd modpagespeed
	gclient sync --force --jobs=1
	cd ..
    else
	mkdir modpagespeed
	cd modpagespeed
	gclient config http://modpagespeed.googlecode.com/svn/trunk/src
	gclient sync --force --jobs=1
    fi
    cd ..
    mv -f Makefile modpagespeed/src/install
}
initMPS