#!/bin/bash

export BUILD_ROOT=`pwd`;


. `pwd`/versions

mkdir -p /app/vendor


export BUILD_ROOT=`pwd`;
export BUILD_DIR=$BUILD_ROOT/httpd-$HTTPD_VERSION

clean() {
    rm -rf *.tar.gz*
    rm -rf *.tgz
}

pcre() {
    rm -rf pcre-$PCRE_VERSION
    echo "Downloading pcre $PCRE_VERSION"
    curl -k --progress-bar -L -O ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$PCRE_VERSION.tar.gz
    tar -xzvf pcre-$PCRE_VERSION.tar.gz
    
    cd pcre-$PCRE_VERSION
    export PCRE_DIR=/app/vendor/pcre
    ./configure --prefix=$PCRE_DIR
    make
    make install
    cd ..
}

apache() {
    pcre
    rm -rf httpd-$HTTPD_VERSION
    echo "Downloading apache $VERSION"
    curl -k --progress-bar -L -O http://mirrors.ukfast.co.uk/sites/ftp.apache.org//httpd/httpd-$HTTPD_VERSION.tar.gz
    echo "Downloading apache-apr $APR_VERSION"
    curl -k --progress-bar -L -O http://mirror.ox.ac.uk/sites/rsync.apache.org//apr/apr-$APR_VERSION.tar.gz
    echo "Downloading apache-apr-util $APR_UTIL_VERSION"
    curl -k --progress-bar -L -O http://mirrors.ukfast.co.uk/sites/ftp.apache.org//apr/apr-util-$APR_UTIL_VERSION.tar.gz
    
    tar -xzvf httpd-$HTTPD_VERSION.tar.gz
    tar -xzvf apr-$APR_VERSION.tar.gz
    tar -xzvf apr-util-$APR_UTIL_VERSION.tar.gz
    
    mv $BUILD_ROOT/apr-$APR_VERSION $BUILD_ROOT/httpd-$HTTPD_VERSION/srclib/apr
    mv $BUILD_ROOT/apr-util-$APR_UTIL_VERSION $BUILD_ROOT/httpd-$HTTPD_VERSION/srclib/apr-util
    
    cd httpd-$HTTPD_VERSION
    ./configure --prefix=/app/apache --with-apr=`pwd`/srclib/apr --with-included-apr --with-pcre=$PCRE_DIR --with-mpm=prefork \
    --with-suexec-docroot=/app/www \
    --disable-charset-lite \
    --disable-include \
    --disable-setenvif \
    --disable-status \
    --disable-autoindex \
    --disable-asis \
    --disable-cgi \
    --disable-negotiation \
    --disable-imap \
    --disable-actions \
    --disable-userdir \
    --disable-alias \
    --enable-env \
    --enable-mods-shared \
    --enable-deflate \
    --enable-expies \
    --enable-rewrite \
    --enable-ssl \
    --enable-vhost-alias \
    --enable-modules='unixd access_compat filter env deflate rewrite auth_basic'

    make
    make install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/apache/lib
    cd ..
    mkdir /app/www
}

installNcurses() {

    echo "Downloading ncurses $NCURSES_VERSION"
    curl -k --progress-bar -L -O http://ftp.gnu.org/pub/gnu/ncurses/ncurses-$NCURSES_VERSION.tar.gz
    tar -xzvf ncurses-$NCURSES_VERSION.tar.gz

    cd ncurses-$NCURSES_VERSION
    ./configure --prefix=/app/vendor/ncurses
    make
    make install
    cd ..
}

installPython() {
    installNcurses
    
    echo "Downloading python $PYTHON_VERSION"
    curl -k --progress-bar -L -O http://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz   
    tar -xzvf Python-$PYTHON_VERSION.tgz
    
    cd Python-$PYTHON_VERSION
    ./configure --prefix=/app/vendor/python
    make
    make install
    cd ..
}

installGperf() {
    echo "Downloading gperf $GPERF_VERSION"
    curl -k --progress-bar -L -O http://ftp.gnu.org/pub/gnu/gperf/gperf-$GPERF_VERSION.tar.gz
    tar -xzvf gperf-$GPERF_VERSION.tar.gz
    
    cd gperf-$GPERF_VERSION
    ./configure --prefix=/app/vendor/gperf
    make
    make install
    export PATH=$PATH:/app/vendor/gperf/bin
    cd ..
}

modpagespeed() {
    installPython
    installGperf
    export PATH=$PATH:`pwd`/bin/depot_tools

    cd modpagespeed
    python src/tools/clang/scripts/update.py
    python src/build/gyp_chromium -Dchromium_revision=161115
    cd src
    make AR.host=`pwd`/build/wrappers/ar.sh AR.target=`pwd`/build/wrappers/ar.sh BUILDTYPE=Release
    cd install
    #APXS_BIN=/app/apache/bin/apxs ./install_apxs.sh
    make APACHE_ROOT=/app/apache APACHE_MODULES=/app/apache/modules APACHE_CONTROL_PROGRAM=/etc/init.d/httpd APACHE_USER=daemon APACHE_DOC_ROOT=/app/www staging
    make install
    cd ../../..
}

php() {
    rm -rf php-$PHP_VERSION
    echo "Downloading php $PHP_VERSION"
    curl -k --progress-bar -L -o php-$PHP_VERSION.tar.gz http://uk1.php.net/get/php-$PHP_VERSION.tar.gz/from/this/mirror
    tar -xzvf php-$PHP_VERSION.tar.gz
    cd php-$PHP_VERSION
    ./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs \
    --with-config-file-scan-dir=/app/www/.php \
    --with-mpm=worker \
    --with-bz2 \
    --with-curl \
    --with-zlib-dir \
    --with-zlib \
    --with-pcre-regex=/app/vendor/pcre \
    --without-sqlite \
    --without-mysql \
    --enable-opcache \
    --enable-fpm
    make
    make install
    cd ..
    
    /app/php/bin/pecl install mongo
    chmod 755 /app/php/lib/php/extensions/no-debug-non-zts-20121212/mongo.so
}

node() {
	rm -rf node-v$NODE_VERSION
	echo "Downloading node $NODE_VERSION"
	curl -k --progress-bar -L -O http://nodejs.org/dist/v0.10.26/node-v$NODE_VERSION.tar.gz
	
	tar -xzvf node-v$NODE_VERSION.tar.gz
	cd node-v$NODE_VERSION
	./configure --prefix=/app/node
	make
	make install
	cd ..
	/app/node/bin/npm install -g grunt \
	grunt-cli \
	sass \
	yuicompressor \
	sqwish \
	node-minify

}

clean

apache
#modpagespeed
php
node

clean
