#!/bin/bash

. `pwd`/versions

mkdir -p /app/vendor

sh ./get_deps

export BUILD_ROOT=`pwd`;
export BUILD_DIR=$BUILD_ROOT/httpd-$VERSION

pcre() {
    cd pcre-$PCRE_VERSION
    export PCRE_DIR=/app/vendor/pcre
    ./configure --prefix=$PCRE_DIR
    make
    make install
    cd ..
}

apache() {
    pcre
    cd httpd-$VERSION
    ./configure --prefix=/app/apache --with-apr=`pwd`/srclib/apr --with-included-apr --with-pcre=$PCRE_DIR --with-mpm=prefork \
    --with-suexec-docroot=/app/www \
    --disable-charset-lite \
    --disable-include \
    --disable-setenvif \
    --disable-status \
    --disable-autoindex \
    --disable-asis \
    --disable-cgi \
    --disable-negotiation \
    --disable-imap \
    --disable-actions \
    --disable-userdir \
    --disable-alias \
    --enable-env \
    --enable-mods-shared \
    --enable-deflate \
    --enable-expies \
    --enable-rewrite \
    --enable-ssl \
    --enable-vhost-alias \
    --enable-modules='unixd access_compat filter env deflate rewrite auth_basic'

    make
    make install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/apache/lib
    cd ..
    mkdir /app/www
}

installNcurses() {
    cd ncurses-$NCURSES_VERSION
    ./configure --prefix=/app/vendor/ncurses
    make
    make install
    cd ..
}

installPython() {
    installNcurses
    cd Python-$PYTHON_VERSION
    ./configure --prefix=/app/vendor/python
    make
    make install
    cd ..
}

installGperf() {
    cd gperf-$GPERF_VERSION
    ./configure --prefix=/app/vendor/gperf
    make
    make install
    export PATH=$PATH:/app/vendor/gperf/bin
    cd ..
}

modpagespeed() {
    installPython
    installGperf
    export PATH=$PATH:`pwd`/bin/depot_tools

    cd modpagespeed
    python src/tools/clang/scripts/update.py
    python src/build/gyp_chromium -Dchromium_revision=161115
    cd src
    make AR.host=`pwd`/build/wrappers/ar.sh AR.target=`pwd`/build/wrappers/ar.sh BUILDTYPE=Release
    cd install
    #APXS_BIN=/app/apache/bin/apxs ./install_apxs.sh
    make APACHE_ROOT=/app/apache APACHE_MODULES=/app/apache/modules APACHE_CONTROL_PROGRAM=/etc/init.d/httpd APACHE_USER=daemon APACHE_DOC_ROOT=/app/www staging
    make install
    cd ../../..
}

php() {
    cd php-$PHP_VERSION
    ./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs \
    --with-config-file-scan-dir=/app/www/.php \
    --with-mpm=worker \
    --with-bz2 \
    --with-curl \
    --with-zlib-dir \
    --with-zlib \
    --with-pcre-regex=/app/vendor/pcre \
    --without-sqlite \
    --without-mysql \
    --enable-opcache \
    --enable-fpm
    make
    make install
    cd ..
    
    /app/php/bin/pecl install mongo
    /app/php/bin/pecl install apc
    
}

apache
#modpagespeed
php
